// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mekkhhrccyepxlsbqspp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1la2toaHJjY3llcHhsc2Jxc3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjI1MDQsImV4cCI6MjA2NDY5ODUwNH0.Lcg7Wf3bb1PohiUTJVW4fnN0x16wdG0bT_yQTwedvOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);